package edu.bnu.hmss.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "hoteldb")
public class Customer implements java.io.Serializable {

	private Integer customerId;
	private Employee employee;
	private String firstName;
	private String lastName;
	private String address;
	private String city;
	private Integer phoneNo;
	private String email;
	private Integer cnic;
	private String custNationality;
	private Set<Reservation> reservations = new HashSet<Reservation>(0);

	public Customer() {
	}

	public Customer(Employee employee) {
		this.employee = employee;
	}

	public Customer(Employee employee, String firstName, String lastName,
			String address, String city, Integer phoneNo, String email,
			Integer cnic, String custNationality, Set<Reservation> reservations) {
		this.employee = employee;
		this.firstName = firstName;
		this.lastName = lastName;
		this.address = address;
		this.city = city;
		this.phoneNo = phoneNo;
		this.email = email;
		this.cnic = cnic;
		this.custNationality = custNationality;
		this.reservations = reservations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CustomerId", unique = true, nullable = false)
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EmpId", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Column(name = "FirstName", length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LastName", length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "Address", length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "City", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "PhoneNo")
	public Integer getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(Integer phoneNo) {
		this.phoneNo = phoneNo;
	}

	@Column(name = "Email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "CNIC")
	public Integer getCnic() {
		return this.cnic;
	}

	public void setCnic(Integer cnic) {
		this.cnic = cnic;
	}

	@Column(name = "CustNationality", length = 45)
	public String getCustNationality() {
		return this.custNationality;
	}

	public void setCustNationality(String custNationality) {
		this.custNationality = custNationality;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Reservation> getReservations() {
		return this.reservations;
	}

	public void setReservations(Set<Reservation> reservations) {
		this.reservations = reservations;
	}

}
