package edu.bnu.hmss.entity;
// Generated Oct 3, 2014 4:33:30 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "hoteldb")
public class Employee implements java.io.Serializable {

	private Integer empId;
	private Hotel hotel;
	private Users users;
	private String empName;
	private String empAddress;
	private Integer empCnic;
	private String empCity;
	private Integer empContactNo;
	private String employeeDesignationId;
	private Set<Customer> customers = new HashSet<Customer>(0);

	public Employee() {
	}

	public Employee(Hotel hotel, Users users, String employeeDesignationId) {
		this.hotel = hotel;
		this.users = users;
		this.employeeDesignationId = employeeDesignationId;
	}

	public Employee(Hotel hotel, Users users, String empName,
			String empAddress, Integer empCnic, String empCity,
			Integer empContactNo, String employeeDesignationId,
			Set<Customer> customers) {
		this.hotel = hotel;
		this.users = users;
		this.empName = empName;
		this.empAddress = empAddress;
		this.empCnic = empCnic;
		this.empCity = empCity;
		this.empContactNo = empContactNo;
		this.employeeDesignationId = employeeDesignationId;
		this.customers = customers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "EmpId", unique = true, nullable = false)
	public Integer getEmpId() {
		return this.empId;
	}

	public void setEmpId(Integer empId) {
		this.empId = empId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Hotel_HotelId", nullable = false)
	public Hotel getHotel() {
		return this.hotel;
	}

	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "username", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "EmpName", length = 45)
	public String getEmpName() {
		return this.empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	@Column(name = "EmpAddress", length = 45)
	public String getEmpAddress() {
		return this.empAddress;
	}

	public void setEmpAddress(String empAddress) {
		this.empAddress = empAddress;
	}

	@Column(name = "EmpCNIC")
	public Integer getEmpCnic() {
		return this.empCnic;
	}

	public void setEmpCnic(Integer empCnic) {
		this.empCnic = empCnic;
	}

	@Column(name = "EmpCity", length = 45)
	public String getEmpCity() {
		return this.empCity;
	}

	public void setEmpCity(String empCity) {
		this.empCity = empCity;
	}

	@Column(name = "EmpContactNo")
	public Integer getEmpContactNo() {
		return this.empContactNo;
	}

	public void setEmpContactNo(Integer empContactNo) {
		this.empContactNo = empContactNo;
	}

	@Column(name = "EmployeeDesignation_id", nullable = false, length = 13)
	public String getEmployeeDesignationId() {
		return this.employeeDesignationId;
	}

	public void setEmployeeDesignationId(String employeeDesignationId) {
		this.employeeDesignationId = employeeDesignationId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set<Customer> getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}

}
