package edu.bnu.hmss.entity;
// Generated Oct 3, 2014 4:33:30 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Hotel generated by hbm2java
 */
@Entity
@Table(name = "hotel", catalog = "hoteldb")
public class Hotel implements java.io.Serializable {

	private Integer hotelId;
	private Users users;
	private String name;
	private String city;
	private Integer contactNumber;
	private String address;
	private Set<Floor> floors = new HashSet<Floor>(0);
	private Set<Employee> employees = new HashSet<Employee>(0);

	public Hotel() {
	}

	public Hotel(Users users) {
		this.users = users;
	}

	public Hotel(Users users, String name, String city, Integer contactNumber,
			String address, Set<Floor> floors, Set<Employee> employees) {
		this.users = users;
		this.name = name;
		this.city = city;
		this.contactNumber = contactNumber;
		this.address = address;
		this.floors = floors;
		this.employees = employees;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "HotelId", unique = true, nullable = false)
	public Integer getHotelId() {
		return this.hotelId;
	}

	public void setHotelId(Integer hotelId) {
		this.hotelId = hotelId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "username", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "Name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "City", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "ContactNumber")
	public Integer getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(Integer contactNumber) {
		this.contactNumber = contactNumber;
	}

	@Column(name = "Address", length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hotel")
	public Set<Floor> getFloors() {
		return this.floors;
	}

	public void setFloors(Set<Floor> floors) {
		this.floors = floors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hotel")
	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

}
