package edu.bnu.hmss.entity;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reservation generated by hbm2java
 */
@Entity
@Table(name = "reservation", catalog = "hoteldb")
public class Reservation implements java.io.Serializable {

	private Integer reservationId;
	private Customer customer;
	private String reservationName;
	private Date arrivalDate;
	private Date departureDate;
	private Set<Roombooking> roombookings = new HashSet<Roombooking>(0);

	public Reservation() {
	}

	public Reservation(Customer customer) {
		this.customer = customer;
	}

	public Reservation(Customer customer, String reservationName,
			Date arrivalDate, Date departureDate, Set<Roombooking> roombookings) {
		this.customer = customer;
		this.reservationName = reservationName;
		this.arrivalDate = arrivalDate;
		this.departureDate = departureDate;
		this.roombookings = roombookings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ReservationId", unique = true, nullable = false)
	public Integer getReservationId() {
		return this.reservationId;
	}

	public void setReservationId(Integer reservationId) {
		this.reservationId = reservationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Customer_CustomerId", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "ReservationName", length = 45)
	public String getReservationName() {
		return this.reservationName;
	}

	public void setReservationName(String reservationName) {
		this.reservationName = reservationName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ArrivalDate", length = 10)
	public Date getArrivalDate() {
		return this.arrivalDate;
	}

	public void setArrivalDate(Date arrivalDate) {
		this.arrivalDate = arrivalDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DepartureDate", length = 10)
	public Date getDepartureDate() {
		return this.departureDate;
	}

	public void setDepartureDate(Date departureDate) {
		this.departureDate = departureDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reservation")
	public Set<Roombooking> getRoombookings() {
		return this.roombookings;
	}

	public void setRoombookings(Set<Roombooking> roombookings) {
		this.roombookings = roombookings;
	}

}
