package edu.bnu.hmss.entity;
// Generated Oct 3, 2014 4:33:30 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Roombooking generated by hbm2java
 */
@Entity
@Table(name = "roombooking", catalog = "hoteldb")
public class Roombooking implements java.io.Serializable {

	private Integer roomBookingId;
	private Room room;
	private Reservation reservation;
	private Date checkin;
	private Date checkout;
	private Set<Services> serviceses = new HashSet<Services>(0);

	public Roombooking() {
	}

	public Roombooking(Room room, Reservation reservation) {
		this.room = room;
		this.reservation = reservation;
	}

	public Roombooking(Room room, Reservation reservation, Date checkin,
			Date checkout, Set<Services> serviceses) {
		this.room = room;
		this.reservation = reservation;
		this.checkin = checkin;
		this.checkout = checkout;
		this.serviceses = serviceses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "RoomBookingId", unique = true, nullable = false)
	public Integer getRoomBookingId() {
		return this.roomBookingId;
	}

	public void setRoomBookingId(Integer roomBookingId) {
		this.roomBookingId = roomBookingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Room_RoomId", nullable = false)
	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Reservation_ReservationId", nullable = false)
	public Reservation getReservation() {
		return this.reservation;
	}

	public void setReservation(Reservation reservation) {
		this.reservation = reservation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Checkin", length = 10)
	public Date getCheckin() {
		return this.checkin;
	}

	public void setCheckin(Date checkin) {
		this.checkin = checkin;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Checkout", length = 10)
	public Date getCheckout() {
		return this.checkout;
	}

	public void setCheckout(Date checkout) {
		this.checkout = checkout;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roombooking")
	public Set<Services> getServiceses() {
		return this.serviceses;
	}

	public void setServiceses(Set<Services> serviceses) {
		this.serviceses = serviceses;
	}

}
