package edu.bnu.hmss.entity;
// Generated Oct 3, 2014 4:33:30 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Roomtype generated by hbm2java
 */
@Entity
@Table(name = "roomtype", catalog = "hoteldb")
public class Roomtype implements java.io.Serializable {

	private Integer typeId;
	private String roomType;
	private String description;
	private String roomPrice;
	private Set<Room> rooms = new HashSet<Room>(0);

	public Roomtype() {
	}

	public Roomtype(String roomType, String description, String roomPrice,
			Set<Room> rooms) {
		this.roomType = roomType;
		this.description = description;
		this.roomPrice = roomPrice;
		this.rooms = rooms;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TypeId", unique = true, nullable = false)
	public Integer getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	@Column(name = "roomType", length = 11)
	public String getRoomType() {
		return this.roomType;
	}

	public void setRoomType(String roomType) {
		this.roomType = roomType;
	}

	@Column(name = "Description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "RoomPrice", length = 5)
	public String getRoomPrice() {
		return this.roomPrice;
	}

	public void setRoomPrice(String roomPrice) {
		this.roomPrice = roomPrice;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roomtype")
	public Set<Room> getRooms() {
		return this.rooms;
	}

	public void setRooms(Set<Room> rooms) {
		this.rooms = rooms;
	}

}
