package edu.bnu.hmss.entity;
// Generated Oct 3, 2014 4:33:30 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Room generated by hbm2java
 */
@Entity
@Table(name = "room", catalog = "hoteldb")
public class Room implements java.io.Serializable {

	private Integer roomId;
	private Roomtype roomtype;
	private Floor floor;
	private Integer roomNumber;
	private String roomType;
	private Integer roomRate;
	private String roomStatus;
	private String roomAccomodation;
	private Set<Roombooking> roombookings = new HashSet<Roombooking>(0);

	public Room() {
	}

	public Room(Roomtype roomtype, Floor floor) {
		this.roomtype = roomtype;
		this.floor = floor;
	}

	public Room(Roomtype roomtype, Floor floor, Integer roomNumber,
			String roomType, Integer roomRate, String roomStatus,
			String roomAccomodation, Set<Roombooking> roombookings) {
		this.roomtype = roomtype;
		this.floor = floor;
		this.roomNumber = roomNumber;
		this.roomType = roomType;
		this.roomRate = roomRate;
		this.roomStatus = roomStatus;
		this.roomAccomodation = roomAccomodation;
		this.roombookings = roombookings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "RoomId", unique = true, nullable = false)
	public Integer getRoomId() {
		return this.roomId;
	}

	public void setRoomId(Integer roomId) {
		this.roomId = roomId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RoomType_TypeId", nullable = false)
	public Roomtype getRoomtype() {
		return this.roomtype;
	}

	public void setRoomtype(Roomtype roomtype) {
		this.roomtype = roomtype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Floor_FloorId", nullable = false)
	public Floor getFloor() {
		return this.floor;
	}

	public void setFloor(Floor floor) {
		this.floor = floor;
	}

	@Column(name = "RoomNumber")
	public Integer getRoomNumber() {
		return this.roomNumber;
	}

	public void setRoomNumber(Integer roomNumber) {
		this.roomNumber = roomNumber;
	}

	@Column(name = "RoomType", length = 45)
	public String getRoomType() {
		return this.roomType;
	}

	public void setRoomType(String roomType) {
		this.roomType = roomType;
	}

	@Column(name = "RoomRate")
	public Integer getRoomRate() {
		return this.roomRate;
	}

	public void setRoomRate(Integer roomRate) {
		this.roomRate = roomRate;
	}

	@Column(name = "RoomStatus", length = 45)
	public String getRoomStatus() {
		return this.roomStatus;
	}

	public void setRoomStatus(String roomStatus) {
		this.roomStatus = roomStatus;
	}

	@Column(name = "RoomAccomodation", length = 45)
	public String getRoomAccomodation() {
		return this.roomAccomodation;
	}

	public void setRoomAccomodation(String roomAccomodation) {
		this.roomAccomodation = roomAccomodation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "room")
	public Set<Roombooking> getRoombookings() {
		return this.roombookings;
	}

	public void setRoombookings(Set<Roombooking> roombookings) {
		this.roombookings = roombookings;
	}

}
