package edu.bnu.hmss.entity;
// Generated Oct 3, 2014 4:33:30 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Services generated by hbm2java
 */
@Entity
@Table(name = "services", catalog = "hoteldb")
public class Services implements java.io.Serializable {

	private Integer serviceid;
	private Roombooking roombooking;
	private String services;
	private String serviceCharges;

	public Services() {
	}

	public Services(Roombooking roombooking, String serviceCharges) {
		this.roombooking = roombooking;
		this.serviceCharges = serviceCharges;
	}

	public Services(Roombooking roombooking, String services,
			String serviceCharges) {
		this.roombooking = roombooking;
		this.services = services;
		this.serviceCharges = serviceCharges;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Serviceid", unique = true, nullable = false)
	public Integer getServiceid() {
		return this.serviceid;
	}

	public void setServiceid(Integer serviceid) {
		this.serviceid = serviceid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RoomBookingId", nullable = false)
	public Roombooking getRoombooking() {
		return this.roombooking;
	}

	public void setRoombooking(Roombooking roombooking) {
		this.roombooking = roombooking;
	}

	@Column(name = "services", length = 10)
	public String getServices() {
		return this.services;
	}

	public void setServices(String services) {
		this.services = services;
	}

	@Column(name = "service_charges", nullable = false, length = 4)
	public String getServiceCharges() {
		return this.serviceCharges;
	}

	public void setServiceCharges(String serviceCharges) {
		this.serviceCharges = serviceCharges;
	}

}
