package edu.bnu.Lcs.entity;

import java.util.Date;

/**
 * CompanyHead generated by hbm2java
 */
public class CompanyHead {

	private Long companyHeadId;
	private String companyName;
	private Long companyId;
	private Long userId;
	private Date userStarDate;
	private Date userStartTime;
	private Long block;
	private Long amount;

	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public Long getAmount() {
		return amount;
	}

	public void setAmount(Long amount) {
		this.amount = amount;
	}

	public Long getBlock() {
		return block;
	}

	public void setBlock(Long block) {
		this.block = block;
	}

	public Long getCompanyId() {
		return companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	public Long getCompanyHeadId() {
		return this.companyHeadId;
	}

	public void setCompanyHeadId(Long companyHeadId) {
		this.companyHeadId = companyHeadId;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Date getUserStarDate() {
		return this.userStarDate;
	}

	public void setUserStarDate(Date userStarDate) {
		this.userStarDate = userStarDate;
	}

	public Date getUserStartTime() {
		return this.userStartTime;
	}

	public void setUserStartTime(Date userStartTime) {
		this.userStartTime = userStartTime;
	}

}
