package edu.bnu.Lcs.entity;

/**
 * DriverInfo generated by hbm2java
 */
public class DriverInfo {

	private Long driverInfoId;
	private String driverFirstName;
	private String driverLastName;
	private Long driverContactNumber;
	private Long driverCnic;
	private String driverAddress;
	private long status;
	private long usersId;
	private Long block;

	public Long getBlock() {
		return block;
	}

	public void setBlock(Long block) {
		this.block = block;
	}

	public Long getDriverInfoId() {
		return this.driverInfoId;
	}

	public void setDriverInfoId(Long driverInfoId) {
		this.driverInfoId = driverInfoId;
	}

	public String getDriverFirstName() {
		return this.driverFirstName;
	}

	public void setDriverFirstName(String driverFirstName) {
		this.driverFirstName = driverFirstName;
	}

	public String getDriverLastName() {
		return this.driverLastName;
	}

	public void setDriverLastName(String driverLastName) {
		this.driverLastName = driverLastName;
	}

	public Long getDriverContactNumber() {
		return this.driverContactNumber;
	}

	public void setDriverContactNumber(Long driverContactNumber) {
		this.driverContactNumber = driverContactNumber;
	}

	public Long getDriverCnic() {
		return this.driverCnic;
	}

	public void setDriverCnic(Long driverCnic) {
		this.driverCnic = driverCnic;
	}

	public String getDriverAddress() {
		return this.driverAddress;
	}

	public void setDriverAddress(String driverAddress) {
		this.driverAddress = driverAddress;
	}

	public long getStatus() {
		return this.status;
	}

	public void setStatus(long status) {
		this.status = status;
	}

	public long getUsersId() {
		return this.usersId;
	}

	public void setUsersId(long usersId) {
		this.usersId = usersId;
	}

}
