package edu.bnu.Lcs.entity;

import java.sql.Date;
import java.sql.Time;

/**
 * Transactions generated by hbm2java
 */
public class Transactions {
	private String companyName;
	private Long transactionsId;
	private Long companyHeadId;
	private Long accountHeadId;
	private Long driverInfoId;
	private Date transactionDate;
	private Time transactionTime;
	private Long transactionsAmount;
	private String transactionsRemaks;
	private String transactionsMode;
	private Long transportInfoId;
	private Long usersId;

	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public Long getDriverInfoId() {
		return driverInfoId;
	}

	public void setDriverInfoId(Long driverInfoId) {
		this.driverInfoId = driverInfoId;
	}

	public Long getUsersId() {
		return usersId;
	}

	public void setUsersId(Long usersId) {
		this.usersId = usersId;
	}

	public Long getTransportInfoId() {
		return transportInfoId;
	}

	public void setTransportInfoId(Long transportInfoId) {
		this.transportInfoId = transportInfoId;
	}

	public Long getTransactionsId() {
		return this.transactionsId;
	}

	public Time getTransactionTime() {
		return transactionTime;
	}

	public void setTransactionTime(Time transactionTime) {
		this.transactionTime = transactionTime;
	}

	public void setTransactionsId(Long transactionsId) {
		this.transactionsId = transactionsId;
	}

	public Long getCompanyHeadId() {
		return companyHeadId;
	}

	public void setCompanyHeadId(Long companyHeadId) {
		this.companyHeadId = companyHeadId;
	}

	public Long getAccountHeadId() {
		return accountHeadId;
	}

	public void setAccountHeadId(Long accountHeadId) {
		this.accountHeadId = accountHeadId;
	}

	public Date getTransactionDate() {
		return this.transactionDate;
	}

	public void setTransactionDate(Date transactionDate) {
		this.transactionDate = transactionDate;
	}

	public Long getTransactionsAmount() {
		return this.transactionsAmount;
	}

	public void setTransactionsAmount(Long transactionsAmount) {
		this.transactionsAmount = transactionsAmount;
	}

	public String getTransactionsRemaks() {
		return this.transactionsRemaks;
	}

	public void setTransactionsRemaks(String transactionsRemaks) {
		this.transactionsRemaks = transactionsRemaks;
	}

	public String getTransactionsMode() {
		return this.transactionsMode;
	}

	public void setTransactionsMode(String transactionsMode) {
		this.transactionsMode = transactionsMode;
	}

}
