package edu.bnu.Lcs.entity;

import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users {

	private Long usersId;
	private String userName;
	private String userPassword;
	private String firstName;
	private String lastName;
	private String userCnic;
	private long contactNumber;
	private String userEmialid;
	private Date startDate;
	private Date startTime;
	private String role;
	private long status;
	private long block;

	public Long getUsersId() {
		return this.usersId;
	}

	public void setUsersId(Long usersId) {
		this.usersId = usersId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getUserCnic() {
		return this.userCnic;
	}

	public void setUserCnic(String userCnic) {
		this.userCnic = userCnic;
	}

	public long getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(long contactNumber) {
		this.contactNumber = contactNumber;
	}

	public String getUserEmialid() {
		return this.userEmialid;
	}

	public void setUserEmialid(String userEmialid) {
		this.userEmialid = userEmialid;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public long getStatus() {
		return this.status;
	}

	public void setStatus(long status) {
		this.status = status;
	}

	public long getBlock() {
		return this.block;
	}

	public void setBlock(long block) {
		this.block = block;
	}

}
