package edu.bnu.projects.foody.entity;

/**
 * FoodItemsReview generated by hbm2java
 */
public class FoodItemsReview {

	private Long foodItemsReviewId;
	private FoodItems foodItems;
	private Users users;
	private String foodItemsReviewRating;
	private String foodItemsReviewDescription;

	private long resturantId;
	private long foodTypeId;
	private long usersId;
	private long foodItemsId;
	private long foodItemsReviewPending;
	private long foodItemsReviewBlocked;
	private String foodItemName;
	private String foodTypeName;
	private String resturantName;

	public String getFoodItemName() {
		return foodItemName;
	}

	public void setFoodItemName(String foodItemName) {
		this.foodItemName = foodItemName;
	}

	public String getFoodTypeName() {
		return foodTypeName;
	}

	public void setFoodTypeName(String foodTypeName) {
		this.foodTypeName = foodTypeName;
	}

	public String getResturantName() {
		return resturantName;
	}

	public void setResturantName(String resturantName) {
		this.resturantName = resturantName;
	}

	public long getFoodItemsReviewPending() {
		return foodItemsReviewPending;
	}

	public void setFoodItemsReviewPending(long foodItemsReviewPending) {
		this.foodItemsReviewPending = foodItemsReviewPending;
	}

	public long getFoodItemsReviewBlocked() {
		return foodItemsReviewBlocked;
	}

	public void setFoodItemsReviewBlocked(long foodItemsReviewBlocked) {
		this.foodItemsReviewBlocked = foodItemsReviewBlocked;
	}

	public long getResturantId() {
		return resturantId;
	}

	public void setResturantId(long resturantId) {
		this.resturantId = resturantId;
	}

	public long getFoodTypeId() {
		return foodTypeId;
	}

	public void setFoodTypeId(long foodTypeId) {
		this.foodTypeId = foodTypeId;
	}

	public long getUsersId() {
		return usersId;
	}

	public void setUsersId(long usersId) {
		this.usersId = usersId;
	}

	public long getFoodItemsId() {
		return foodItemsId;
	}

	public void setFoodItemsId(long foodItemsId) {
		this.foodItemsId = foodItemsId;
	}

	public Long getFoodItemsReviewId() {
		return this.foodItemsReviewId;
	}

	public void setFoodItemsReviewId(Long foodItemsReviewId) {
		this.foodItemsReviewId = foodItemsReviewId;
	}

	public FoodItems getFoodItems() {
		return this.foodItems;
	}

	public void setFoodItems(FoodItems foodItems) {
		this.foodItems = foodItems;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getFoodItemsReviewRating() {
		return this.foodItemsReviewRating;
	}

	public void setFoodItemsReviewRating(String foodItemsReviewRating) {
		this.foodItemsReviewRating = foodItemsReviewRating;
	}

	public String getFoodItemsReviewDescription() {
		return this.foodItemsReviewDescription;
	}

	public void setFoodItemsReviewDescription(String foodItemsReviewDescription) {
		this.foodItemsReviewDescription = foodItemsReviewDescription;
	}

}
