package edu.bnu.projects.foody.entity;

/**
 * FoodType generated by hbm2java
 */
public class FoodType {

	private Long foodTypeId;
	private Resturant resturant;
	private Users users;
	private String foodTypeName;
	private Long usersId;
	private Long resturantId;
	private long foodTypePending;
	private long foodTypeBlocked;
	private String resturantName;
	// private Set<FoodItems> foodItemses = new HashSet<FoodItems>(0);

	public String getResturantName() {
		return resturantName;
	}

	public void setResturantName(String resturantName) {
		this.resturantName = resturantName;
	}

	public Long getUsersId() {
		return usersId;
	}

	public Long getResturantId() {
		return resturantId;
	}

	public void setResturantId(Long resturantId) {
		this.resturantId = resturantId;
	}

	public void setUsersId(Long usersId) {
		this.usersId = usersId;
	}

	public long getFoodTypePending() {
		return foodTypePending;
	}

	public void setFoodTypePending(long foodTypePending) {
		this.foodTypePending = foodTypePending;
	}

	public long getFoodTypeBlocked() {
		return foodTypeBlocked;
	}

	public void setFoodTypeBlocked(long foodTypeBlocked) {
		this.foodTypeBlocked = foodTypeBlocked;
	}

	public FoodType() {
	}

	public Long getFoodTypeId() {
		return this.foodTypeId;
	}

	public void setFoodTypeId(Long foodTypeId) {
		this.foodTypeId = foodTypeId;
	}

	public Resturant getResturant() {
		return this.resturant;
	}

	public void setResturant(Resturant resturant) {
		this.resturant = resturant;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getFoodTypeName() {
		return this.foodTypeName;
	}

	public void setFoodTypeName(String foodTypeName) {
		this.foodTypeName = foodTypeName;
	}

}
