package edu.bnu.projects.foody.entity;
/**
 * Location generated by hbm2java
 */
public class Location {

	private Long locationId;
	private Resturant resturant;
	private Users users;
	private String locationName;
	private String locationAddress;
	private String locationLat;
	private String locationLon;

	public Long getLocationId() {
		return this.locationId;
	}

	public void setLocationId(Long locationId) {
		this.locationId = locationId;
	}

	public Resturant getResturant() {
		return this.resturant;
	}

	public void setResturant(Resturant resturant) {
		this.resturant = resturant;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getLocationName() {
		return this.locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

	public String getLocationAddress() {
		return this.locationAddress;
	}

	public void setLocationAddress(String locationAddress) {
		this.locationAddress = locationAddress;
	}

	public String getLocationLat() {
		return this.locationLat;
	}

	public void setLocationLat(String locationLat) {
		this.locationLat = locationLat;
	}

	public String getLocationLon() {
		return this.locationLon;
	}

	public void setLocationLon(String locationLon) {
		this.locationLon = locationLon;
	}

}
