package edu.bnu.projects.foody.entity;

/**
 * Resturant generated by hbm2java
 */
public class Resturant {

	private Long resturantId;
	private Users users;
	private String resturantName;
	private int resturantPending;
	private int resturantBlocked;
	private long usersId;

	public long getUsersId() {
		return usersId;
	}

	public void setUsersId(long usersId) {
		this.usersId = usersId;
	}

	public int getResturantPending() {
		return resturantPending;
	}

	public void setResturantPending(int resturantPending) {
		this.resturantPending = resturantPending;
	}

	public int getResturantBlocked() {
		return resturantBlocked;
	}

	public void setResturantBlocked(int resturantBlocked) {
		this.resturantBlocked = resturantBlocked;
	}

	public Long getResturantId() {
		return this.resturantId;
	}

	public void setResturantId(Long resturantId) {
		this.resturantId = resturantId;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getResturantName() {
		return this.resturantName;
	}

	public void setResturantName(String resturantName) {
		this.resturantName = resturantName;
	}

}
