package edu.bnu.projects.foody.entity;

/**
 * ResturantRating generated by hbm2java
 */
public class ResturantRating {

	private Long resturantRatingId;
	private Resturant resturant;
	private Users users;
	private long resturantRatingEnvirnoment;
	private long resturantRatingService;
	private long resturantRatingFood;
	private String resturantRatingDescription;

	public Long getResturantRatingId() {
		return this.resturantRatingId;
	}

	public void setResturantRatingId(Long resturantRatingId) {
		this.resturantRatingId = resturantRatingId;
	}

	public Resturant getResturant() {
		return this.resturant;
	}

	public void setResturant(Resturant resturant) {
		this.resturant = resturant;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public long getResturantRatingEnvirnoment() {
		return this.resturantRatingEnvirnoment;
	}

	public void setResturantRatingEnvirnoment(long resturantRatingEnvirnoment) {
		this.resturantRatingEnvirnoment = resturantRatingEnvirnoment;
	}

	public long getResturantRatingService() {
		return this.resturantRatingService;
	}

	public void setResturantRatingService(long resturantRatingService) {
		this.resturantRatingService = resturantRatingService;
	}

	public long getResturantRatingFood() {
		return this.resturantRatingFood;
	}

	public void setResturantRatingFood(long resturantRatingFood) {
		this.resturantRatingFood = resturantRatingFood;
	}

	public String getResturantRatingDescription() {
		return this.resturantRatingDescription;
	}

	public void setResturantRatingDescription(String resturantRatingDescription) {
		this.resturantRatingDescription = resturantRatingDescription;
	}

}
