package com.project.freefay.entity;

// Generated Dec 23, 2015 6:18:07 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AuthoritiesId generated by hbm2java
 */
@Embeddable
public class AuthoritiesId implements java.io.Serializable {

	private long authoritiesId;
	private String username;
	private long usersId;

	public AuthoritiesId() {
	}

	public AuthoritiesId(long authoritiesId, String username, long usersId) {
		this.authoritiesId = authoritiesId;
		this.username = username;
		this.usersId = usersId;
	}

	@Column(name = "authorities_id", nullable = false)
	public long getAuthoritiesId() {
		return this.authoritiesId;
	}

	public void setAuthoritiesId(long authoritiesId) {
		this.authoritiesId = authoritiesId;
	}

	@Column(name = "username", nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "users_id", nullable = false)
	public long getUsersId() {
		return this.usersId;
	}

	public void setUsersId(long usersId) {
		this.usersId = usersId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AuthoritiesId))
			return false;
		AuthoritiesId castOther = (AuthoritiesId) other;

		return (this.getAuthoritiesId() == castOther.getAuthoritiesId())
				&& ((this.getUsername() == castOther.getUsername()) || (this
						.getUsername() != null
						&& castOther.getUsername() != null && this
						.getUsername().equals(castOther.getUsername())))
				&& (this.getUsersId() == castOther.getUsersId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getAuthoritiesId();
		result = 37 * result
				+ (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37 * result + (int) this.getUsersId();
		return result;
	}

}
