package com.project.freefay.entity;

// Generated Dec 23, 2015 6:18:07 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cities generated by hbm2java
 */
@Entity
@Table(name = "cities", catalog = "freefay")
public class Cities implements java.io.Serializable {

	private long citiesId;
	private String countryCode;
	private String region;
	private String name;
	private double latitude;
	private double longitude;
	private Set<Users> userses = new HashSet<Users>(0);

	public Cities() {
	}

	public Cities(long citiesId, String countryCode, String region,
			String name, double latitude, double longitude) {
		this.citiesId = citiesId;
		this.countryCode = countryCode;
		this.region = region;
		this.name = name;
		this.latitude = latitude;
		this.longitude = longitude;
	}

	public Cities(long citiesId, String countryCode, String region,
			String name, double latitude, double longitude, Set<Users> userses) {
		this.citiesId = citiesId;
		this.countryCode = countryCode;
		this.region = region;
		this.name = name;
		this.latitude = latitude;
		this.longitude = longitude;
		this.userses = userses;
	}

	@Id
	@Column(name = "cities_id", unique = true, nullable = false)
	public long getCitiesId() {
		return this.citiesId;
	}

	public void setCitiesId(long citiesId) {
		this.citiesId = citiesId;
	}

	@Column(name = "country_code", nullable = false, length = 3)
	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	@Column(name = "region", nullable = false, length = 3)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "latitude", nullable = false, precision = 22, scale = 0)
	public double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", nullable = false, precision = 22, scale = 0)
	public double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cities")
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
