package com.project.freefay.entity;

// Generated Dec 23, 2015 6:18:07 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompanyNotification generated by hbm2java
 */
@Entity
@Table(name = "company_notification", catalog = "freefay")
public class CompanyNotification implements java.io.Serializable {

	private Long companyNotificationId;
	private Users users;
	private Date date;
	private Date time;
	private String notificationType;
	private String notificationSubject;
	private String description;
	private Date sendingDate;
	private Date sendingTime;
	private int active;
	private int cancelled;
	private int blocked;

	public CompanyNotification() {
	}

	public CompanyNotification(Users users, Date date, Date time,
			String notificationType, String notificationSubject,
			String description, Date sendingDate, Date sendingTime, int active,
			int cancelled, int blocked) {
		this.users = users;
		this.date = date;
		this.time = time;
		this.notificationType = notificationType;
		this.notificationSubject = notificationSubject;
		this.description = description;
		this.sendingDate = sendingDate;
		this.sendingTime = sendingTime;
		this.active = active;
		this.cancelled = cancelled;
		this.blocked = blocked;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "company_notification_id", unique = true, nullable = false)
	public Long getCompanyNotificationId() {
		return this.companyNotificationId;
	}

	public void setCompanyNotificationId(Long companyNotificationId) {
		this.companyNotificationId = companyNotificationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "admin_id", referencedColumnName = "users_id", nullable = false),
			@JoinColumn(name = "admin_username", referencedColumnName = "username", nullable = false) })
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "time", nullable = false, length = 8)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "notification_type", nullable = false, length = 8)
	public String getNotificationType() {
		return this.notificationType;
	}

	public void setNotificationType(String notificationType) {
		this.notificationType = notificationType;
	}

	@Column(name = "notification_subject", nullable = false, length = 50)
	public String getNotificationSubject() {
		return this.notificationSubject;
	}

	public void setNotificationSubject(String notificationSubject) {
		this.notificationSubject = notificationSubject;
	}

	@Column(name = "description", nullable = false, length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "sending_date", nullable = false, length = 10)
	public Date getSendingDate() {
		return this.sendingDate;
	}

	public void setSendingDate(Date sendingDate) {
		this.sendingDate = sendingDate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "sending_time", nullable = true, length = 8)
	public Date getSendingTime() {
		return this.sendingTime;
	}

	public void setSendingTime(Date sendingTime) {
		this.sendingTime = sendingTime;
	}

	@Column(name = "active", nullable = false)
	public int getActive() {
		return this.active;
	}

	public void setActive(int active) {
		this.active = active;
	}

	@Column(name = "cancelled", nullable = false)
	public int getCancelled() {
		return this.cancelled;
	}

	public void setCancelled(int cancelled) {
		this.cancelled = cancelled;
	}

	@Column(name = "blocked", nullable = false)
	public int getBlocked() {
		return this.blocked;
	}

	public void setBlocked(int blocked) {
		this.blocked = blocked;
	}

}
