package com.project.freefay.entity;

// Generated Dec 23, 2015 6:18:07 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Countries generated by hbm2java
 */
@Entity
@Table(name = "countries", catalog = "freefay")
public class Countries implements java.io.Serializable {

	private Long countriesId;
	private String code;
	private String name;
	private Double latitude;
	private Double longitude;
	private Set<Users> userses = new HashSet<Users>(0);
	private Set<CountryRestrictions> countryRestrictionses = new HashSet<CountryRestrictions>(
			0);

	public Countries() {
	}

	public Countries(String code, String name, Double latitude,
			Double longitude, Set<Users> userses,
			Set<CountryRestrictions> countryRestrictionses) {
		this.code = code;
		this.name = name;
		this.latitude = latitude;
		this.longitude = longitude;
		this.userses = userses;
		this.countryRestrictionses = countryRestrictionses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "countries_id", unique = true, nullable = false)
	public Long getCountriesId() {
		return this.countriesId;
	}

	public void setCountriesId(Long countriesId) {
		this.countriesId = countriesId;
	}

	@Column(name = "code", length = 6)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", length = 150)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "latitude", precision = 22, scale = 0)
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", precision = 22, scale = 0)
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "countries")
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "countries")
	public Set<CountryRestrictions> getCountryRestrictionses() {
		return this.countryRestrictionses;
	}

	public void setCountryRestrictionses(
			Set<CountryRestrictions> countryRestrictionses) {
		this.countryRestrictionses = countryRestrictionses;
	}

}
