package com.project.freefay.entity;

// Generated Dec 23, 2015 6:18:07 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CountryRestrictions generated by hbm2java
 */
@Entity
@Table(name = "country restrictions", catalog = "freefay")
public class CountryRestrictions implements java.io.Serializable {

	private Long countryRestrictionsId;
	private Users users;
	private Countries countries;
	private Portfolio portfolio;
	private String type;
	private long typeId;

	public CountryRestrictions() {
	}

	public CountryRestrictions(Users users, Countries countries,
			Portfolio portfolio, String type, long typeId) {
		this.users = users;
		this.countries = countries;
		this.portfolio = portfolio;
		this.type = type;
		this.typeId = typeId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "country restrictions_id", unique = true, nullable = false)
	public Long getCountryRestrictionsId() {
		return this.countryRestrictionsId;
	}

	public void setCountryRestrictionsId(Long countryRestrictionsId) {
		this.countryRestrictionsId = countryRestrictionsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "users_id", referencedColumnName = "users_id", nullable = false),
			@JoinColumn(name = "username", referencedColumnName = "username", nullable = false) })
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "countries_id", nullable = false)
	public Countries getCountries() {
		return this.countries;
	}

	public void setCountries(Countries countries) {
		this.countries = countries;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "portfolio_id", nullable = false)
	public Portfolio getPortfolio() {
		return this.portfolio;
	}

	public void setPortfolio(Portfolio portfolio) {
		this.portfolio = portfolio;
	}

	@Column(name = "type", nullable = false, length = 11)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "type_id", nullable = false)
	public long getTypeId() {
		return this.typeId;
	}

	public void setTypeId(long typeId) {
		this.typeId = typeId;
	}

}
