package com.project.freefay.entity;

// Generated Dec 23, 2015 6:18:07 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Currencies generated by hbm2java
 */
@Entity
@Table(name = "currencies", catalog = "freefay")
public class Currencies implements java.io.Serializable {

	private Integer idCountries;
	private String name;
	private String isoAlpha2;
	private String isoAlpha3;
	private Integer isoNumeric;
	private String currencyCode;
	private String currencyName;
	private String currrencySymbol;
	private String flag;

	public Currencies() {
	}

	public Currencies(String name, String isoAlpha2, String isoAlpha3,
			Integer isoNumeric, String currencyCode, String currencyName,
			String currrencySymbol, String flag) {
		this.name = name;
		this.isoAlpha2 = isoAlpha2;
		this.isoAlpha3 = isoAlpha3;
		this.isoNumeric = isoNumeric;
		this.currencyCode = currencyCode;
		this.currencyName = currencyName;
		this.currrencySymbol = currrencySymbol;
		this.flag = flag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_countries", unique = true, nullable = false)
	public Integer getIdCountries() {
		return this.idCountries;
	}

	public void setIdCountries(Integer idCountries) {
		this.idCountries = idCountries;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "iso_alpha2", length = 2)
	public String getIsoAlpha2() {
		return this.isoAlpha2;
	}

	public void setIsoAlpha2(String isoAlpha2) {
		this.isoAlpha2 = isoAlpha2;
	}

	@Column(name = "iso_alpha3", length = 3)
	public String getIsoAlpha3() {
		return this.isoAlpha3;
	}

	public void setIsoAlpha3(String isoAlpha3) {
		this.isoAlpha3 = isoAlpha3;
	}

	@Column(name = "iso_numeric")
	public Integer getIsoNumeric() {
		return this.isoNumeric;
	}

	public void setIsoNumeric(Integer isoNumeric) {
		this.isoNumeric = isoNumeric;
	}

	@Column(name = "currency_code", length = 3)
	public String getCurrencyCode() {
		return this.currencyCode;
	}

	public void setCurrencyCode(String currencyCode) {
		this.currencyCode = currencyCode;
	}

	@Column(name = "currency_name", length = 32)
	public String getCurrencyName() {
		return this.currencyName;
	}

	public void setCurrencyName(String currencyName) {
		this.currencyName = currencyName;
	}

	@Column(name = "currrency_symbol", length = 3)
	public String getCurrrencySymbol() {
		return this.currrencySymbol;
	}

	public void setCurrrencySymbol(String currrencySymbol) {
		this.currrencySymbol = currrencySymbol;
	}

	@Column(name = "flag", length = 6)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

}
