package com.project.freefay.entity;

// Generated Dec 23, 2015 6:18:07 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GroupAttachments generated by hbm2java
 */
@Entity
@Table(name = "group_attachments", catalog = "freefay")
public class GroupAttachments implements java.io.Serializable {

	private Long groupAttachmentsId;
	private Attachments attachments;
	private Date date;
	private Date time;
	private Integer blocked;
	private String type;
	private long typeId;

	public GroupAttachments() {
	}

	public GroupAttachments(Attachments attachments, String type, long typeId) {
		this.attachments = attachments;
		this.type = type;
		this.typeId = typeId;
	}

	public GroupAttachments(Attachments attachments, Date date, Date time,
			Integer blocked, String type, long typeId) {
		this.attachments = attachments;
		this.date = date;
		this.time = time;
		this.blocked = blocked;
		this.type = type;
		this.typeId = typeId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "group_attachments_id", unique = true, nullable = false)
	public Long getGroupAttachmentsId() {
		return this.groupAttachmentsId;
	}

	public void setGroupAttachmentsId(Long groupAttachmentsId) {
		this.groupAttachmentsId = groupAttachmentsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "attachments_id", nullable = false)
	public Attachments getAttachments() {
		return this.attachments;
	}

	public void setAttachments(Attachments attachments) {
		this.attachments = attachments;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "time", length = 8)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "blocked")
	public Integer getBlocked() {
		return this.blocked;
	}

	public void setBlocked(Integer blocked) {
		this.blocked = blocked;
	}

	@Column(name = "type", nullable = false, length = 12)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "type_id", nullable = false)
	public long getTypeId() {
		return this.typeId;
	}

	public void setTypeId(long typeId) {
		this.typeId = typeId;
	}

}
