package com.project.freefay.entity;

// Generated Dec 23, 2015 6:18:07 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PaymentOptions generated by hbm2java
 */
@Entity
@Table(name = "payment_options", catalog = "freefay")
public class PaymentOptions implements java.io.Serializable {

	private Long paymentOptionsId;
	private Users users;
	private String paymentName;
	private Date date;
	private Date time;
	private int active;
	private int blocked;
	private Set<Payment> payments = new HashSet<Payment>(0);

	public PaymentOptions() {
	}

	public PaymentOptions(Users users, String paymentName, Date date,
			Date time, int active, int blocked) {
		this.users = users;
		this.paymentName = paymentName;
		this.date = date;
		this.time = time;
		this.active = active;
		this.blocked = blocked;
	}

	public PaymentOptions(Users users, String paymentName, Date date,
			Date time, int active, int blocked, Set<Payment> payments) {
		this.users = users;
		this.paymentName = paymentName;
		this.date = date;
		this.time = time;
		this.active = active;
		this.blocked = blocked;
		this.payments = payments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "payment_options_id", unique = true, nullable = false)
	public Long getPaymentOptionsId() {
		return this.paymentOptionsId;
	}

	public void setPaymentOptionsId(Long paymentOptionsId) {
		this.paymentOptionsId = paymentOptionsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "admin_id", referencedColumnName = "users_id", nullable = false),
			@JoinColumn(name = "admin_username", referencedColumnName = "username", nullable = false) })
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "payment_name", nullable = false, length = 45)
	public String getPaymentName() {
		return this.paymentName;
	}

	public void setPaymentName(String paymentName) {
		this.paymentName = paymentName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "time", nullable = false, length = 8)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "active", nullable = false)
	public int getActive() {
		return this.active;
	}

	public void setActive(int active) {
		this.active = active;
	}

	@Column(name = "blocked", nullable = false)
	public int getBlocked() {
		return this.blocked;
	}

	public void setBlocked(int blocked) {
		this.blocked = blocked;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paymentOptions")
	public Set<Payment> getPayments() {
		return this.payments;
	}

	public void setPayments(Set<Payment> payments) {
		this.payments = payments;
	}

}
