package com.project.freefay.entity;

// Generated Dec 23, 2015 6:18:07 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ratings generated by hbm2java
 */
@Entity
@Table(name = "ratings", catalog = "freefay")
public class Ratings implements java.io.Serializable {

	private Long ratingsId;
	private Users usersByFkRatingsUsers1;
	private Users usersByFkRatingsUsers2;
	private Portfolio portfolio;
	private Date date;
	private Date time;
	private int active;
	private int blocked;
	private String type;
	private long typeId;
	private String review;
	private String rating;

	public Ratings() {
	}

	public Ratings(Users usersByFkRatingsUsers1, Users usersByFkRatingsUsers2,
			Portfolio portfolio, Date date, Date time, int active, int blocked,
			String type, long typeId, String review, String rating) {
		this.usersByFkRatingsUsers1 = usersByFkRatingsUsers1;
		this.usersByFkRatingsUsers2 = usersByFkRatingsUsers2;
		this.portfolio = portfolio;
		this.date = date;
		this.time = time;
		this.active = active;
		this.blocked = blocked;
		this.type = type;
		this.typeId = typeId;
		this.review = review;
		this.rating = rating;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ratings_id", unique = true, nullable = false)
	public Long getRatingsId() {
		return this.ratingsId;
	}

	public void setRatingsId(Long ratingsId) {
		this.ratingsId = ratingsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "users_id", referencedColumnName = "users_id", nullable = false),
			@JoinColumn(name = "username", referencedColumnName = "username", nullable = false) })
	public Users getUsersByFkRatingsUsers1() {
		return this.usersByFkRatingsUsers1;
	}

	public void setUsersByFkRatingsUsers1(Users usersByFkRatingsUsers1) {
		this.usersByFkRatingsUsers1 = usersByFkRatingsUsers1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "reviewer_id", referencedColumnName = "users_id", nullable = false),
			@JoinColumn(name = "reviewer_username", referencedColumnName = "username", nullable = false) })
	public Users getUsersByFkRatingsUsers2() {
		return this.usersByFkRatingsUsers2;
	}

	public void setUsersByFkRatingsUsers2(Users usersByFkRatingsUsers2) {
		this.usersByFkRatingsUsers2 = usersByFkRatingsUsers2;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "portfolio_id", nullable = false)
	public Portfolio getPortfolio() {
		return this.portfolio;
	}

	public void setPortfolio(Portfolio portfolio) {
		this.portfolio = portfolio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "time", nullable = false, length = 8)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "active", nullable = false)
	public int getActive() {
		return this.active;
	}

	public void setActive(int active) {
		this.active = active;
	}

	@Column(name = "blocked", nullable = false)
	public int getBlocked() {
		return this.blocked;
	}

	public void setBlocked(int blocked) {
		this.blocked = blocked;
	}

	@Column(name = "type", nullable = false, length = 11)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "type_id", nullable = false)
	public long getTypeId() {
		return this.typeId;
	}

	public void setTypeId(long typeId) {
		this.typeId = typeId;
	}

	@Column(name = "review", nullable = false, length = 150)
	public String getReview() {
		return this.review;
	}

	public void setReview(String review) {
		this.review = review;
	}

	@Column(name = "rating", nullable = false, length = 2)
	public String getRating() {
		return this.rating;
	}

	public void setRating(String rating) {
		this.rating = rating;
	}

}
