package com.project.freefay.entity;

// Generated Dec 23, 2015 6:18:07 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Regions generated by hbm2java
 */
@Entity
@Table(name = "regions", catalog = "freefay", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "country", "code" }),
		@UniqueConstraint(columnNames = { "country", "name" }) })
public class Regions implements java.io.Serializable {

	private Integer id;
	private String country;
	private String code;
	private String name;
	private double latitude;
	private double longitude;
	private int cities;
	private Set<Users> userses = new HashSet<Users>(0);

	public Regions() {
	}

	public Regions(String country, String code, String name, double latitude,
			double longitude, int cities) {
		this.country = country;
		this.code = code;
		this.name = name;
		this.latitude = latitude;
		this.longitude = longitude;
		this.cities = cities;
	}

	public Regions(String country, String code, String name, double latitude,
			double longitude, int cities, Set<Users> userses) {
		this.country = country;
		this.code = code;
		this.name = name;
		this.latitude = latitude;
		this.longitude = longitude;
		this.cities = cities;
		this.userses = userses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "country", nullable = false, length = 2)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "code", nullable = false, length = 3)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "latitude", nullable = false, precision = 22, scale = 0)
	public double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", nullable = false, precision = 22, scale = 0)
	public double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}

	@Column(name = "cities", nullable = false)
	public int getCities() {
		return this.cities;
	}

	public void setCities(int cities) {
		this.cities = cities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "regions")
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
