package com.project.freefay.entity;

// Generated Dec 23, 2015 6:18:07 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Services generated by hbm2java
 */
@Entity
@Table(name = "services", catalog = "freefay")
public class Services implements java.io.Serializable {

	private Long servicesId;
	private Users users;
	private Portfolio portfolio;
	private Category category;
	private SubCategory subCategory;
	private Fields fields;
	private String serviceName;
	private Double budget;
	private int tipsEnabled;
	private String timeLimit;
	private Date date;
	private Date time;
	private Integer active;
	private Integer blocked;
	private String description;
	private Set<Search> searches = new HashSet<Search>(0);
	private Set<Views> viewses = new HashSet<Views>(0);

	public Services() {
	}

	public Services(Users users, Portfolio portfolio, int tipsEnabled) {
		this.users = users;
		this.portfolio = portfolio;
		this.tipsEnabled = tipsEnabled;
	}

	public Services(Users users, Portfolio portfolio, Category category,
			SubCategory subCategory, Fields fields, String serviceName,
			Double budget, int tipsEnabled, String timeLimit, Date date,
			Date time, Integer active, Integer blocked, Set<Search> searches,
			Set<Views> viewses) {
		this.users = users;
		this.portfolio = portfolio;
		this.category = category;
		this.subCategory = subCategory;
		this.fields = fields;
		this.serviceName = serviceName;
		this.budget = budget;
		this.tipsEnabled = tipsEnabled;
		this.timeLimit = timeLimit;
		this.date = date;
		this.time = time;
		this.active = active;
		this.blocked = blocked;
		this.searches = searches;
		this.viewses = viewses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "services_id", unique = true, nullable = false)
	public Long getServicesId() {
		return this.servicesId;
	}

	public void setServicesId(Long servicesId) {
		this.servicesId = servicesId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumns({
			@JoinColumn(name = "users_id", referencedColumnName = "users_id", nullable = false),
			@JoinColumn(name = "username", referencedColumnName = "username", nullable = false) })
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "category_id", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "sub_category_id", nullable = false)
	public SubCategory getSubCategory() {
		return this.subCategory;
	}

	public void setSubCategory(SubCategory subCategory) {
		this.subCategory = subCategory;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "fields_id", nullable = false)
	public Fields getFields() {
		return fields;
	}

	public void setFields(Fields fields) {
		this.fields = fields;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "portfolio_id", nullable = false)
	public Portfolio getPortfolio() {
		return this.portfolio;
	}

	public void setPortfolio(Portfolio portfolio) {
		this.portfolio = portfolio;
	}

	@Column(name = "service_name", length = 45)
	public String getServiceName() {
		return this.serviceName;
	}

	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

	@Column(name = "budget", precision = 22, scale = 0)
	public Double getBudget() {
		return this.budget;
	}

	public void setBudget(Double budget) {
		this.budget = budget;
	}

	@Column(name = "tips_enabled", nullable = false)
	public int getTipsEnabled() {
		return this.tipsEnabled;
	}

	public void setTipsEnabled(int tipsEnabled) {
		this.tipsEnabled = tipsEnabled;
	}

	@Column(name = "time_limit", length = 50)
	public String getTimeLimit() {
		return this.timeLimit;
	}

	public void setTimeLimit(String timeLimit) {
		this.timeLimit = timeLimit;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "time", length = 8)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "active")
	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

	@Column(name = "blocked")
	public Integer getBlocked() {
		return this.blocked;
	}

	public void setBlocked(Integer blocked) {
		this.blocked = blocked;
	}

	@Column(name = "description", length = 1000)
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "services")
	public Set<Search> getSearches() {
		return this.searches;
	}

	public void setSearches(Set<Search> searches) {
		this.searches = searches;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "services")
	public Set<Views> getViewses() {
		return this.viewses;
	}

	public void setViewses(Set<Views> viewses) {
		this.viewses = viewses;
	}

}
