package com.project.freefay.entity;

// Generated Dec 23, 2015 6:18:07 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Subscription generated by hbm2java
 */
@Entity
@Table(name = "subscription", catalog = "freefay")
public class Subscription implements java.io.Serializable {

	private Long subscriptionId;
	private Users users;
	private String subscriptionType;
	private Date date;
	private Date time;
	private int blocked;
	private Set<UserSubscription> userSubscriptions = new HashSet<UserSubscription>(
			0);

	public Subscription() {
	}

	public Subscription(Users users, String subscriptionType, Date date,
			Date time, int blocked) {
		this.users = users;
		this.subscriptionType = subscriptionType;
		this.date = date;
		this.time = time;
		this.blocked = blocked;
	}

	public Subscription(Users users, String subscriptionType, Date date,
			Date time, int blocked, Set<UserSubscription> userSubscriptions) {
		this.users = users;
		this.subscriptionType = subscriptionType;
		this.date = date;
		this.time = time;
		this.blocked = blocked;
		this.userSubscriptions = userSubscriptions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "subscription_id", unique = true, nullable = false)
	public Long getSubscriptionId() {
		return this.subscriptionId;
	}

	public void setSubscriptionId(Long subscriptionId) {
		this.subscriptionId = subscriptionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "admin_id", referencedColumnName = "users_id", nullable = false),
			@JoinColumn(name = "admin_username", referencedColumnName = "username", nullable = false) })
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "subscription_type", nullable = false, length = 2)
	public String getSubscriptionType() {
		return this.subscriptionType;
	}

	public void setSubscriptionType(String subscriptionType) {
		this.subscriptionType = subscriptionType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "time", nullable = false, length = 8)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "blocked", nullable = false)
	public int getBlocked() {
		return this.blocked;
	}

	public void setBlocked(int blocked) {
		this.blocked = blocked;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subscription")
	public Set<UserSubscription> getUserSubscriptions() {
		return this.userSubscriptions;
	}

	public void setUserSubscriptions(Set<UserSubscription> userSubscriptions) {
		this.userSubscriptions = userSubscriptions;
	}

}
