package com.project.freefay.entity;

// Generated Dec 23, 2015 6:18:07 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsersId generated by hbm2java
 */
@Embeddable
public class UsersId implements java.io.Serializable {

	private long usersId;
	private String username;

	public UsersId() {
	}

	public UsersId(long usersId, String username) {
		this.usersId = usersId;
		this.username = username;
	}

	@Column(name = "users_id", nullable = false)
	public long getUsersId() {
		return this.usersId;
	}

	public void setUsersId(long usersId) {
		this.usersId = usersId;
	}

	@Column(name = "username", nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsersId))
			return false;
		UsersId castOther = (UsersId) other;

		return (this.getUsersId() == castOther.getUsersId())
				&& ((this.getUsername() == castOther.getUsername()) || (this
						.getUsername() != null
						&& castOther.getUsername() != null && this
						.getUsername().equals(castOther.getUsername())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUsersId();
		result = 37 * result
				+ (getUsername() == null ? 0 : this.getUsername().hashCode());
		return result;
	}

}
