package com.project.freefay.entity;

// Generated Dec 23, 2015 6:18:07 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserDuration generated by hbm2java
 */
@Entity
@Table(name = "user_duration", catalog = "freefay")
public class UserDuration implements java.io.Serializable {

	private Long userDurationId;
	private Users users;
	private Date loginTime;
	private Date loginDate;
	private Date logoutTime;
	private Date logoutDate;

	public UserDuration() {
	}

	public UserDuration(Users users) {
		this.users = users;
	}

	public UserDuration(Users users, Date loginTime, Date loginDate,
			Date logoutTime, Date logoutDate) {
		this.users = users;
		this.loginTime = loginTime;
		this.loginDate = loginDate;
		this.logoutTime = logoutTime;
		this.logoutDate = logoutDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_duration_id", unique = true, nullable = false)
	public Long getUserDurationId() {
		return this.userDurationId;
	}

	public void setUserDurationId(Long userDurationId) {
		this.userDurationId = userDurationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "users_id", referencedColumnName = "users_id", nullable = false),
			@JoinColumn(name = "username", referencedColumnName = "username", nullable = false) })
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "login_time", length = 8)
	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "login_date", length = 10)
	public Date getLoginDate() {
		return this.loginDate;
	}

	public void setLoginDate(Date loginDate) {
		this.loginDate = loginDate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "logout_time", length = 8)
	public Date getLogoutTime() {
		return this.logoutTime;
	}

	public void setLogoutTime(Date logoutTime) {
		this.logoutTime = logoutTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "logout_date", length = 10)
	public Date getLogoutDate() {
		return this.logoutDate;
	}

	public void setLogoutDate(Date logoutDate) {
		this.logoutDate = logoutDate;
	}

}
