package com.project.freefay.entity;

// Generated Dec 23, 2015 6:18:07 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserPoints generated by hbm2java
 */
@Entity
@Table(name = "user_points", catalog = "freefay")
public class UserPoints implements java.io.Serializable {

	private Long userPointsId;
	private UserSubscription userSubscription;
	private Date date;
	private Date time;
	private Integer block;
	private Integer points;

	public UserPoints() {
	}

	public UserPoints(UserSubscription userSubscription) {
		this.userSubscription = userSubscription;
	}

	public UserPoints(UserSubscription userSubscription, Date date, Date time,
			Integer block, Integer points) {
		this.userSubscription = userSubscription;
		this.date = date;
		this.time = time;
		this.block = block;
		this.points = points;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_points_id", unique = true, nullable = false)
	public Long getUserPointsId() {
		return this.userPointsId;
	}

	public void setUserPointsId(Long userPointsId) {
		this.userPointsId = userPointsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_subscription_id", nullable = false)
	public UserSubscription getUserSubscription() {
		return this.userSubscription;
	}

	public void setUserSubscription(UserSubscription userSubscription) {
		this.userSubscription = userSubscription;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "time", length = 8)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "block")
	public Integer getBlock() {
		return this.block;
	}

	public void setBlock(Integer block) {
		this.block = block;
	}

	@Column(name = "points")
	public Integer getPoints() {
		return this.points;
	}

	public void setPoints(Integer points) {
		this.points = points;
	}

}
